# Generated by Django 4.2.11 on 2024-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='download_speed',
            field=models.DecimalField(decimal_places=2, help_text='Download speed (Mbps)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='upload_speed',
            field=models.DecimalField(decimal_places=2, help_text='Upload speed (Mbps)', max_digits=5),
        ),
    ]
